# Generated by Django 5.0.6 on 2024-06-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_participant_age_alter_participant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='personal_info',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
