# Generated by Django 5.0.6 on 2024-10-30 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_remove_hall_images'),
        ('participation', '0004_alter_participation_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participation',
            name='description_payment',
        ),
        migrations.AddField(
            model_name='participation',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hall.hall'),
        ),
    ]
