# Generated by Django 5.0.6 on 2024-10-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0005_remove_participation_description_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
