# Generated by Django 5.0.6 on 2024-07-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_editor',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_judge',
            field=models.BooleanField(default=False, help_text='Designates whether the user can grades participants.', verbose_name='Editor Status'),
        ),
    ]
