# Generated by Django 5.0.6 on 2024-07-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_is_editor_customuser_is_judge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_judge',
            field=models.BooleanField(default=False, help_text='Designates whether the user can grades Auditioners.', verbose_name='Judge Status'),
        ),
    ]
