# Generated by Django 5.0.6 on 2024-07-08 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditioner', '0002_rename_competition_auditioner_audition_and_more'),
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='auditioner',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='auditioner.auditioner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
