# Generated by Django 5.0.6 on 2024-07-09 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_participant_auditioner_participant_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='people_coming',
            new_name='amount_people_coming',
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.EmailField(default=' ', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='grade',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='instrument',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='phone',
            field=models.CharField(default=None, max_length=20, validators=[django.core.validators.RegexValidator(regex='^[0-9]')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='school',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='teacher',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
