# Generated by Django 5.0.6 on 2024-10-02 21:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_rename_people_coming_participant_amount_people_coming_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='auditioner',
        ),
        migrations.AddField(
            model_name='participant',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
