# Generated by Django 5.0.6 on 2024-10-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0005_remove_participant_regis_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='applicant_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher'), ('self', 'Self')], default='self', max_length=20),
        ),
    ]
