# Generated by Django 5.0.6 on 2024-10-31 03:42

import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0006_participant_applicant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='shorts_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='shorts_video',
            field=models.FileField(blank=True, null=True, upload_to='auditioner/{id}'),
        ),
    ]
