# Generated by Django 5.0.6 on 2024-07-17 04:06

import datetime
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='competition', max_length=255)),
                ('comp_poster', versatileimagefield.fields.VersatileImageField(upload_to='')),
                ('email', models.EmailField(default='rosha.thailand@gmail.com', max_length=254)),
                ('elig', models.JSONField(max_length=255)),
                ('instr_type', models.JSONField(max_length=255)),
                ('deadline', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('ann_date', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('compet_date', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('descr_payment', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
