# Generated by Django 5.0.6 on 2024-07-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_rename_comp_poster_competition_compt_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='ann_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='compt_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='deadline_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
