# Generated by Django 5.0.6 on 2024-10-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=100)),
                ('location_link', models.URLField(blank=True)),
                ('images', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
