# Generated by Django 5.0.6 on 2024-10-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_alter_hall_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='images',
        ),
    ]
