# Generated by Django 5.0.6 on 2024-11-13 01:01

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_remove_hall_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='images',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default=list, null=True, upload_to=''),
        ),
    ]
