# Generated by Django 5.0.6 on 2024-06-16 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
        ('referee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='average',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='participant.participant'),
        ),
        migrations.AlterField(
            model_name='score',
            name='perform_score',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='score',
            name='rythm_score',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='score',
            name='skill_score',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
