# Generated by Django 5.0.6 on 2024-08-01 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrant', '0004_alter_entrant_age_alter_entrant_elig_and_more'),
        ('referee', '0002_score_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrantScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('rythm_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('perform_score', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('average', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
                ('entrant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrant.entrant')),
            ],
        ),
    ]
