# Generated by Django 5.0.6 on 2024-06-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0002_score_average_alter_score_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='perform_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='score',
            name='rythm_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='score',
            name='skill_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
