# Generated by Django 5.0.6 on 2024-07-05 03:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='category',
            field=models.CharField(default='audition', max_length=255),
        ),
        migrations.AddField(
            model_name='audition',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
