# Generated by Django 5.0.6 on 2024-10-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0002_audition_category_audition_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audition',
            name='announcement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audition',
            name='concert_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audition',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
