# Generated by Django 5.0.6 on 2024-10-15 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0004_alter_audition_announcement_date_and_more'),
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hall.hall'),
        ),
    ]
