# Generated by Django 5.0.6 on 2024-10-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0005_audition_hall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audition',
            name='description_payment',
        ),
        migrations.AddField(
            model_name='audition',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
