# Generated by Django 5.0.6 on 2024-11-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0006_remove_audition_description_payment_audition_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='max_age',
            field=models.PositiveIntegerField(help_text='กำหนดอายุสูงสุดที่อนุญาต', null=True),
        ),
        migrations.AddField(
            model_name='audition',
            name='min_age',
            field=models.PositiveIntegerField(help_text='กำหนดอายุขั้นต่ำที่อนุญาต', null=True),
        ),
    ]
