# Generated by Django 5.0.6 on 2024-11-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0007_audition_max_age_audition_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='elig',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='audition',
            name='max_age',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='audition',
            name='min_age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
