# Generated by Django 5.0.6 on 2024-11-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0008_audition_elig_alter_audition_max_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
