# Generated by Django 5.0.6 on 2024-11-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0009_audition_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audition',
            name='max_age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audition',
            name='min_age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
