# Generated by Django 5.0.6 on 2024-11-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0010_alter_audition_max_age_alter_audition_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='audition',
            name='descprition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audition',
            name='elig',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audition',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
