# Generated by Django 5.0.6 on 2024-11-12 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0011_audition_descprition_alter_audition_elig_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audition',
            old_name='descprition',
            new_name='description',
        ),
    ]
