# Generated by Django 5.0.6 on 2024-11-30 18:56

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0012_rename_descprition_audition_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audition',
            name='image',
        ),
        migrations.AddField(
            model_name='audition',
            name='poster',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='audition/posters/', verbose_name='Image'),
        ),
    ]
