# Generated by Django 5.0.6 on 2024-07-30 06:54

import django.core.serializers.json
import django.core.validators
import django.utils.timezone
import embed_video.fields
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrant',
            name='pers_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entrant',
            name='slip',
            field=versatileimagefield.fields.VersatileImageField(default=django.utils.timezone.now, upload_to='entrant/slips'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrant',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='elig',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='entity',
            field=models.CharField(choices=[('', 'Choose one of the following options'), ('tchrname', 'Teacher Name (If Individual apply)'), ('repname', 'Representative Name (If Group apply)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='instr_type',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='short_url',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='entrant/videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'flv'])]),
        ),
    ]
