# Generated by Django 5.0.6 on 2024-08-01 18:14

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrant', '0003_rename_entity_name_entrant_prim_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrant',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='elig',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='entity',
            field=models.CharField(choices=[('1', 'Individual (apply is alone)'), ('2', 'Group (apply as a team)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='instr_type',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
