# Generated by Django 5.0.6 on 2024-10-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrant', '0004_alter_entrant_age_alter_entrant_elig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrant',
            name='pers_info',
        ),
    ]
