# Generated by Django 5.0.6 on 2024-08-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrant', '0004_alter_entrant_age_alter_entrant_elig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrant',
            name='elig',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entrant',
            name='instr_type',
            field=models.CharField(max_length=255),
        ),
    ]
