# Generated by Django 5.0.6 on 2024-10-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrant', '0006_entrant_applicant_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrant',
            old_name='short_url',
            new_name='shorts_url',
        ),
        migrations.AddField(
            model_name='entrant',
            name='shorts_video',
            field=models.FileField(blank=True, null=True, upload_to='auditioner/{id}'),
        ),
    ]
