# Generated by Django 5.0.6 on 2024-12-06 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrant', '0007_rename_short_url_entrant_shorts_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrant',
            name='elig',
        ),
        migrations.RemoveField(
            model_name='entrant',
            name='instr_type',
        ),
    ]
