# Generated by Django 5.0.6 on 2024-07-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditioner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditioner',
            old_name='competition',
            new_name='audition',
        ),
        migrations.AddField(
            model_name='auditioner',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
