# Generated by Django 5.0.6 on 2024-07-11 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditioner', '0002_rename_competition_auditioner_audition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100)),
                ('auditioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditioner.auditioner')),
            ],
        ),
    ]
