# Generated by Django 5.0.6 on 2024-07-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditioner', '0004_alter_performresult_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformResult',
        ),
    ]
