# Generated by Django 5.0.6 on 2024-10-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditioner', '0006_remove_auditioner_personal_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditioner',
            name='applicant_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('teacher', 'Teacher'), ('self', 'Self')], default='self', max_length=20),
        ),
    ]
