# Generated by Django 5.0.6 on 2024-11-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditioner', '0008_auditioner_shorts_video_alter_auditioner_shorts_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditioner',
            name='applicant_type',
        ),
    ]
