# Generated by Django 5.0.6 on 2024-11-12 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditioner', '0009_remove_auditioner_applicant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditioner',
            name='elig',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
