# Generated by Django 5.0.6 on 2024-11-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditioner', '0010_auditioner_elig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditioner',
            name='elig',
            field=models.CharField(choices=[('adfja;klj', 'adfja;klj'), ('adfjadkj', 'adfjadkj'), ('adfkjadfkljda;', 'adfkjadfkljda;')], default='Unspecified', max_length=255),
        ),
    ]
