# Generated by Django 5.0.6 on 2024-11-13 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditioner', '0011_alter_auditioner_elig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditioner',
            old_name='instrument',
            new_name='instrument_type',
        ),
    ]
