# Generated by Django 5.0.6 on 2024-11-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditioner', '0012_rename_instrument_auditioner_instrument_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditioner',
            name='cpr_permission',
        ),
        migrations.AlterField(
            model_name='auditioner',
            name='instrument_type',
            field=models.CharField(choices=[('adkfljadksljdas;dj', 'adkfljadksljdas;dj'), ('adfjakdfja;lfdk', 'adfjakdfja;lfdk'), ('adfjkadfsjkdslaf', 'adfjkadfsjkdslaf')], default='Unspecified', max_length=255),
        ),
    ]
