# Generated by Django 5.0.6 on 2024-11-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditioner', '0013_remove_auditioner_cpr_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditioner',
            name='elig',
            field=models.CharField(choices=[('adfja;klj', 'adfja;klj'), ('adfjadkj', 'adfjadkj'), ('adfkjadfkljda;', 'adfkjadfkljda;'), ('class A', 'class A'), ('class B', 'class B'), ('class C', 'class C')], default='Unspecified', max_length=255),
        ),
        migrations.AlterField(
            model_name='auditioner',
            name='instrument_type',
            field=models.CharField(choices=[('adkfljadksljdas;dj', 'adkfljadksljdas;dj'), ('adfjakdfja;lfdk', 'adfjakdfja;lfdk'), ('adfjkadfsjkdslaf', 'adfjkadfsjkdslaf'), ('piano', 'piano'), ('all', 'all')], default='Unspecified', max_length=255),
        ),
    ]
