# Generated by Django 5.0.6 on 2024-11-30 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditioner', '0014_alter_auditioner_elig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditioner',
            name='elig',
        ),
        migrations.RemoveField(
            model_name='auditioner',
            name='instrument_type',
        ),
    ]
